<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students [
    <!ELEMENT students (student+)>
    <!ELEMENT student (name, rollno, branch)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT rollno (#PCDATA)>
    <!ELEMENT branch (#PCDATA)>
]>
<students>
    <student>
        <name>Sahil</name>
        <rollno>101</rollno>
        <branch>CSE</branch>
    </student>
    <student>
        <name>Riya</name>
        <rollno>102</rollno>
        <branch>IT</branch>
    </student>
</students>
